package defpackage;

import com.adjust.sdk.Constants;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class bzg {
    public static final azg A;
    public static final azg A0;
    public static final azg B;
    public static final azg B0;
    public static final azg C;
    public static final azg C0;
    public static final azg D;
    public static final azg D0;
    public static final azg E;
    public static final azg E0;
    public static final azg F;
    public static final azg F0;
    public static final azg G;
    public static final azg G0;
    public static final azg H;
    public static final azg H0;
    public static final azg I;
    public static final azg I0;
    public static final azg J;
    public static final azg J0;
    public static final azg K;
    public static final azg K0;
    public static final azg L;
    public static final azg L0;
    public static final azg M;
    public static final azg M0;
    public static final azg N;
    public static final azg N0;
    public static final azg O;
    public static final azg O0;
    public static final azg P;
    public static final azg P0;
    public static final azg Q;
    public static final azg Q0;
    public static final azg R;
    public static final azg R0;
    public static final azg S;
    public static final azg S0;
    public static final azg T;
    public static final azg T0;
    public static final azg U;
    public static final azg U0;
    public static final azg V;
    public static final azg V0;
    public static final azg W;
    public static final azg W0;
    public static final azg X;
    public static final azg X0;
    public static final azg Y;
    public static final azg Y0;
    public static final azg Z;
    public static final azg Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final azg a0;
    public static final azg a1;
    public static final azg b;
    public static final azg b0;
    public static final azg b1;
    public static final azg c;
    public static final azg c0;
    public static final azg c1;
    public static final azg d;
    public static final azg d0;
    public static final azg d1;
    public static final azg e;
    public static final azg e0;
    public static final azg e1;
    public static final azg f;
    public static final azg f0;
    public static final azg f1;
    public static final azg g;
    public static final azg g0;
    public static final azg g1;
    public static final azg h;
    public static final azg h0;
    public static final azg h1;
    public static final azg i;
    public static final azg i0;
    public static final azg i1;
    public static final azg j;
    public static final azg j0;
    public static final azg j1;
    public static final azg k;
    public static final azg k0;
    public static final azg l;
    public static final azg l0;
    public static final azg m;
    public static final azg m0;
    public static final azg n;
    public static final azg n0;
    public static final azg o;
    public static final azg o0;
    public static final azg p;
    public static final azg p0;
    public static final azg q;
    public static final azg q0;
    public static final azg r;
    public static final azg r0;
    public static final azg s;
    public static final azg s0;
    public static final azg t;
    public static final azg t0;
    public static final azg u;
    public static final azg u0;
    public static final azg v;
    public static final azg v0;
    public static final azg w;
    public static final azg w0;
    public static final azg x;
    public static final azg x0;
    public static final azg y;
    public static final azg y0;
    public static final azg z;
    public static final azg z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, jwg.G0, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, pzd.e, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, pzd.w, false);
        e = a("measurement.config.cache_time", 86400000L, g3e.z, false);
        f = a("measurement.config.url_scheme", Constants.SCHEME, w1e.X, false);
        g = a("measurement.config.url_authority", "app-measurement.com", mwg.d, false);
        h = a("measurement.upload.max_bundles", 100, mwg.g, false);
        i = a("measurement.upload.max_batch_size", 65536, mwg.x, false);
        j = a("measurement.upload.max_bundle_size", 65536, jwg.z, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, jwg.Z, false);
        l = a("measurement.upload.max_events_per_day", 100000, pwg.E0, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, w1e.e, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, g3e.g, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, pzd.g, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, uzd.v, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, w1e.f, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", g3e.v, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", pzd.v, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", uzd.w, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", w1e.g, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, g3e.w, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, uzd.x, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, w1e.v, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, g3e.x, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, pzd.x, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, uzd.y, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, w1e.w, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, g3e.y, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, pzd.y, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, uzd.z, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, w1e.x, false);
        G = a("measurement.upload.backoff_period", 43200000L, pzd.z, false);
        a("measurement.upload.window_interval", 3600000L, uzd.X, false);
        H = a("measurement.upload.interval", 3600000L, w1e.y, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, g3e.X, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, pzd.X, false);
        K = a("measurement.upload.minimum_delay", 500L, uzd.Y, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, w1e.z, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, g3e.Y, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, pzd.Y, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, uzd.Z, false);
        P = a("measurement.upload.retry_time", 1800000L, g3e.Z, false);
        Q = a("measurement.upload.retry_count", 6, jwg.b, false);
        R = a("measurement.upload.max_queue_time", 518400000L, mwg.b, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, nwg.b, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, pwg.b, false);
        U = a("measurement.audience.filter_result_max_count", 200, jwg.c, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, mwg.c, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, nwg.c, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, pwg.c, false);
        b0 = a("measurement.test.test_string_flag", "---", jwg.d, false);
        c0 = a("measurement.test.test_long_flag", -1L, nwg.d, false);
        a("measurement.test.test_cached_long_flag", -1L, pwg.d, true);
        d0 = a("measurement.test.test_int_flag", -2, jwg.e, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), mwg.e, false);
        a("measurement.experiment.max_ids", 50, nwg.e, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, pwg.e, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, mwg.f, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, nwg.f, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, pwg.f, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, jwg.f, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, nwg.g, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, pwg.g, false);
        m0 = a("measurement.rb.attribution.uri_scheme", Constants.SCHEME, jwg.g, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", mwg.v, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", nwg.v, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, jwg.v, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", mwg.w, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", nwg.w, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", pwg.v, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", jwg.w, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, nwg.x, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, pwg.w, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, jwg.x, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, mwg.y, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, nwg.y, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, pwg.x, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, jwg.y, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, mwg.z, false);
        a("measurement.config.default_flag_values", bool2, nwg.z, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, pwg.y, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, mwg.X, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, nwg.X, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, pwg.z, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, jwg.X, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, mwg.Y, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, nwg.Y, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, jwg.Y, false);
        K0 = a("measurement.service.store_null_safelist", bool2, mwg.Z, false);
        L0 = a("measurement.service.store_safelist", bool2, nwg.Z, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, pwg.X, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, mwg.E0, true);
        O0 = a("measurement.rb.attribution.service", bool2, nwg.E0, true);
        P0 = a("measurement.rb.attribution.client2", bool2, pwg.Y, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, jwg.E0, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, mwg.F0, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, mwg.I0, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, nwg.F0, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, pwg.Z, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, jwg.F0, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, mwg.G0, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, nwg.G0, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, pzd.d, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, g3e.d, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, g3e.e, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, nwg.H0, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, mwg.H0, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", uzd.f, false);
        c1 = a("measurement.edpb.service", bool, w1e.c, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", w1e.d, false);
        e1 = a("measurement.robust_time_source_2", bool, jwg.H0, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, pwg.F0, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", g3e.f, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", pzd.f, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", uzd.g, false);
        j1 = a("measurement.diagnostics.enabled", bool, uzd.e, false);
    }

    public static azg a(String str, Object obj, msg msgVar, boolean z2) {
        azg azgVar = new azg(str, obj, msgVar);
        if (z2) {
            a.add(azgVar);
        }
        return azgVar;
    }
}
