package defpackage;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes.dex */
public abstract class h82 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = my9.t;
        a = j2;
        b = my9.c;
        c = my9.d;
        d = my9.r;
        long j3 = my9.C;
        e = j3;
        f = my9.i;
        long j4 = my9.f;
        g = j4;
        h = my9.b;
        i = my9.a;
        j = my9.z;
        long j5 = my9.y;
        k = j5;
        l = j5;
        m = my9.A;
        n = my9.F;
        long j6 = my9.E;
        o = j6;
        p = j6;
        q = my9.G;
        r = j4;
        s = my9.u;
        t = my9.L;
        long j7 = my9.K;
        u = j7;
        v = j7;
        w = my9.M;
        x = my9.v;
        y = my9.w;
        z = my9.B;
        long j8 = my9.D;
        A = j8;
        B = j8;
        C = j3;
        D = my9.e;
        E = my9.H;
        long j9 = my9.J;
        F = j9;
        G = j9;
        H = my9.I;
        I = j2;
        J = j2;
        K = my9.q;
        L = my9.p;
        M = my9.o;
        N = my9.s;
        O = my9.g;
        P = my9.n;
        Q = my9.x;
        R = my9.N;
        long j10 = my9.P;
        S = j10;
        T = j10;
        U = my9.O;
    }
}
