package defpackage;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes.dex */
public final class m82 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public u51 W;
    public u51 X;
    public u51 Y;
    public u51 Z;
    public final long a;
    public rp1 a0;
    public final long b;
    public auc b0;
    public final long c;
    public i0f c0;
    public final long d;
    public qy1 d0;
    public final long e;
    public ke3 e0;
    public final long f;
    public cu6 f0;
    public final long g;
    public ku6 g0;
    public final long h;
    public q78 h0;
    public final long i;
    public tr8 i0;
    public final long j;
    public jbb j0;
    public final long k;
    public pod k0;
    public final long l;
    public vbe l0;
    public final long m;
    public wne m0;
    public final long n;
    public wne n0;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public m82(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        ks0.s(this.a, "onPrimary=", sb);
        ks0.s(this.b, "primaryContainer=", sb);
        ks0.s(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        ks0.s(j, "inversePrimary=", sb);
        ks0.s(this.e, "secondary=", sb);
        ks0.s(this.f, "onSecondary=", sb);
        ks0.s(this.g, "secondaryContainer=", sb);
        ks0.s(this.h, "onSecondaryContainer=", sb);
        ks0.s(this.i, "tertiary=", sb);
        ks0.s(this.j, "onTertiary=", sb);
        ks0.s(this.k, "tertiaryContainer=", sb);
        ks0.s(this.l, "onTertiaryContainer=", sb);
        ks0.s(this.m, "background=", sb);
        ks0.s(this.n, "onBackground=", sb);
        ks0.s(this.o, "surface=", sb);
        ks0.s(this.p, "onSurface=", sb);
        ks0.s(this.q, "surfaceVariant=", sb);
        ks0.s(this.r, "onSurfaceVariant=", sb);
        ks0.s(this.s, "surfaceTint=", sb);
        ks0.s(this.t, "inverseSurface=", sb);
        ks0.s(this.u, "inverseOnSurface=", sb);
        ks0.s(this.v, "error=", sb);
        ks0.s(this.w, "onError=", sb);
        ks0.s(this.x, "errorContainer=", sb);
        ks0.s(this.y, "onErrorContainer=", sb);
        ks0.s(this.z, "outline=", sb);
        ks0.s(this.A, "outlineVariant=", sb);
        ks0.s(this.B, "scrim=", sb);
        ks0.s(this.C, "surfaceBright=", sb);
        ks0.s(this.D, "surfaceDim=", sb);
        ks0.s(this.E, "surfaceContainer=", sb);
        ks0.s(this.F, "surfaceContainerHigh=", sb);
        ks0.s(this.G, "surfaceContainerHighest=", sb);
        ks0.s(this.H, "surfaceContainerLow=", sb);
        ks0.s(this.I, "surfaceContainerLowest=", sb);
        ks0.s(this.J, "primaryFixed=", sb);
        ks0.s(this.K, "primaryFixedDim=", sb);
        ks0.s(this.L, "onPrimaryFixed=", sb);
        ks0.s(j, "onPrimaryFixedVariant=", sb);
        ks0.s(this.N, "secondaryFixed=", sb);
        ks0.s(this.O, "secondaryFixedDim=", sb);
        ks0.s(this.P, "onSecondaryFixed=", sb);
        ks0.s(this.Q, "onSecondaryFixedVariant=", sb);
        ks0.s(this.R, "tertiaryFixed=", sb);
        ks0.s(this.S, "tertiaryFixedDim=", sb);
        ks0.s(this.T, "onTertiaryFixed=", sb);
        ks0.s(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) y72.h(this.V));
        sb.append(')');
        return sb.toString();
    }
}
