package defpackage;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes.dex */
public abstract class m8f {
    public static final long A;
    public static final long A0;
    public static final o66 A1;
    public static final long B;
    public static final ar5 B0;
    public static final long B1;
    public static final long C;
    public static final o66 C0;
    public static final long C1;
    public static final ar5 D;
    public static final long D0;
    public static final long D1;
    public static final o66 E;
    public static final long E0;
    public static final ar5 E1;
    public static final long F;
    public static final long F0;
    public static final o66 F1;
    public static final long G;
    public static final ar5 G0;
    public static final long G1;
    public static final long H;
    public static final o66 H0;
    public static final long H1;
    public static final ar5 I;
    public static final long I0;
    public static final long I1;
    public static final o66 J;
    public static final long J0;
    public static final ar5 J1;
    public static final long K;
    public static final long K0;
    public static final o66 K1;
    public static final long L;
    public static final ar5 L0;
    public static final long L1;
    public static final long M;
    public static final o66 M0;
    public static final long M1;
    public static final ar5 N;
    public static final long N0;
    public static final long N1;
    public static final o66 O;
    public static final long O0;
    public static final ar5 O1;
    public static final long P;
    public static final long P0;
    public static final o66 P1;
    public static final long Q;
    public static final ar5 Q0;
    public static final long Q1;
    public static final long R;
    public static final o66 R0;
    public static final long R1;
    public static final ar5 S;
    public static final long S0;
    public static final long S1;
    public static final o66 T;
    public static final long T0;
    public static final ar5 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final ar5 V0;
    public static final long W;
    public static final o66 W0;
    public static final ar5 X;
    public static final long X0;
    public static final o66 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final o66 a;
    public static final long a0;
    public static final ar5 a1;
    public static final long b;
    public static final long b0;
    public static final o66 b1;
    public static final long c;
    public static final ar5 c0;
    public static final long c1;
    public static final long d;
    public static final o66 d0;
    public static final long d1;
    public static final ar5 e;
    public static final long e0;
    public static final long e1;
    public static final o66 f;
    public static final long f0;
    public static final ar5 f1;
    public static final long g;
    public static final long g0;
    public static final o66 g1;
    public static final long h;
    public static final ar5 h0;
    public static final long h1;
    public static final long i;
    public static final o66 i0;
    public static final long i1;
    public static final ar5 j;
    public static final long j0;
    public static final long j1;
    public static final o66 k;
    public static final long k0;
    public static final ar5 k1;
    public static final long l;
    public static final long l0;
    public static final o66 l1;
    public static final long m;
    public static final ar5 m0;
    public static final long m1;
    public static final long n;
    public static final o66 n0;
    public static final long n1;
    public static final ar5 o;
    public static final long o0;
    public static final long o1;
    public static final o66 p;
    public static final long p0;
    public static final ar5 p1;
    public static final long q;
    public static final long q0;
    public static final o66 q1;
    public static final long r;
    public static final ar5 r0;
    public static final long r1;
    public static final long s;
    public static final o66 s0;
    public static final long s1;
    public static final ar5 t;
    public static final long t0;
    public static final long t1;
    public static final o66 u;
    public static final long u0;
    public static final ar5 u1;
    public static final long v;
    public static final long v0;
    public static final o66 v1;
    public static final long w;
    public static final ar5 w0;
    public static final long w1;
    public static final long x;
    public static final o66 x0;
    public static final long x1;
    public static final ar5 y;
    public static final long y0;
    public static final long y1;
    public static final o66 z;
    public static final long z0;
    public static final ar5 z1;

    static {
        ar5 ar5Var = m9f.a;
        o66 o66Var = yp5.b;
        a = o66Var;
        b = w6c.k(24.0d);
        c = w6c.l(16);
        d = w6c.k(0.5d);
        ar5 ar5Var2 = m9f.c;
        e = ar5Var2;
        f = o66Var;
        g = w6c.k(20.0d);
        h = w6c.l(14);
        i = w6c.k(0.2d);
        j = ar5Var2;
        k = o66Var;
        l = w6c.k(16.0d);
        m = w6c.l(12);
        n = w6c.k(0.4d);
        o = ar5Var2;
        p = o66Var;
        q = w6c.k(64.0d);
        r = w6c.l(57);
        long jK = w6c.k(0.2d);
        w6c.f(jK);
        s = w6c.r(jK & 1095216660480L, -wue.c(jK));
        t = ar5Var2;
        u = o66Var;
        v = w6c.k(52.0d);
        w = w6c.l(45);
        x = w6c.k(0.0d);
        y = ar5Var2;
        z = o66Var;
        A = w6c.k(44.0d);
        B = w6c.l(36);
        C = w6c.k(0.0d);
        D = ar5Var2;
        E = o66Var;
        F = w6c.k(40.0d);
        G = w6c.l(32);
        H = w6c.k(0.0d);
        I = ar5Var2;
        J = o66Var;
        K = w6c.k(36.0d);
        L = w6c.l(28);
        M = w6c.k(0.0d);
        N = ar5Var2;
        O = o66Var;
        P = w6c.k(32.0d);
        Q = w6c.l(24);
        R = w6c.k(0.0d);
        S = ar5Var2;
        T = o66Var;
        U = w6c.k(20.0d);
        V = w6c.l(14);
        W = w6c.k(0.1d);
        ar5 ar5Var3 = m9f.b;
        X = ar5Var3;
        Y = o66Var;
        Z = w6c.k(16.0d);
        a0 = w6c.l(12);
        b0 = w6c.k(0.5d);
        c0 = ar5Var3;
        d0 = o66Var;
        e0 = w6c.k(16.0d);
        f0 = w6c.l(11);
        g0 = w6c.k(0.5d);
        h0 = ar5Var3;
        i0 = o66Var;
        j0 = w6c.k(28.0d);
        k0 = w6c.l(22);
        l0 = w6c.k(0.0d);
        m0 = ar5Var2;
        n0 = o66Var;
        o0 = w6c.k(24.0d);
        p0 = w6c.l(16);
        q0 = w6c.k(0.2d);
        r0 = ar5Var3;
        s0 = o66Var;
        t0 = w6c.k(20.0d);
        u0 = w6c.l(14);
        v0 = w6c.k(0.1d);
        w0 = ar5Var3;
        x0 = o66Var;
        y0 = w6c.k(24.0d);
        z0 = w6c.l(16);
        A0 = w6c.k(0.15d);
        B0 = ar5Var3;
        C0 = o66Var;
        D0 = w6c.k(20.0d);
        E0 = w6c.l(14);
        F0 = w6c.k(0.25d);
        G0 = ar5Var3;
        H0 = o66Var;
        I0 = w6c.k(16.0d);
        J0 = w6c.l(12);
        K0 = w6c.k(0.4d);
        L0 = ar5Var3;
        M0 = o66Var;
        N0 = w6c.k(64.0d);
        O0 = w6c.l(57);
        P0 = w6c.l(0);
        Q0 = ar5Var3;
        R0 = o66Var;
        S0 = w6c.k(52.0d);
        T0 = w6c.l(45);
        U0 = w6c.l(0);
        V0 = ar5Var3;
        W0 = o66Var;
        X0 = w6c.k(44.0d);
        Y0 = w6c.l(36);
        Z0 = w6c.l(0);
        a1 = ar5Var3;
        b1 = o66Var;
        c1 = w6c.k(40.0d);
        d1 = w6c.l(32);
        e1 = w6c.l(0);
        f1 = ar5Var3;
        g1 = o66Var;
        h1 = w6c.k(36.0d);
        i1 = w6c.l(28);
        j1 = w6c.l(0);
        k1 = ar5Var3;
        l1 = o66Var;
        m1 = w6c.k(32.0d);
        n1 = w6c.l(24);
        o1 = w6c.l(0);
        p1 = ar5Var3;
        q1 = o66Var;
        r1 = w6c.k(20.0d);
        s1 = w6c.l(14);
        t1 = w6c.k(0.1d);
        ar5 ar5Var4 = m9f.a;
        u1 = ar5Var4;
        v1 = o66Var;
        w1 = w6c.k(16.0d);
        x1 = w6c.l(12);
        y1 = w6c.k(0.5d);
        z1 = ar5Var4;
        A1 = o66Var;
        B1 = w6c.k(16.0d);
        C1 = w6c.l(11);
        D1 = w6c.k(0.5d);
        E1 = ar5Var4;
        F1 = o66Var;
        G1 = w6c.k(28.0d);
        H1 = w6c.l(22);
        I1 = w6c.l(0);
        J1 = ar5Var3;
        K1 = o66Var;
        L1 = w6c.k(24.0d);
        M1 = w6c.l(16);
        N1 = w6c.k(0.15d);
        O1 = ar5Var4;
        P1 = o66Var;
        Q1 = w6c.k(20.0d);
        R1 = w6c.l(14);
        S1 = w6c.k(0.1d);
        T1 = ar5Var4;
    }
}
