package defpackage;

import io.sentry.protocol.DebugImage;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Set;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes3.dex */
public final class pyd {
    public static final j22 A;
    public static final dx5 a;
    public static final dx5 b;
    public static final dx5 c;
    public static final dx5 d;
    public static final dx5 e;
    public static final dx5 f;
    public static final dx5 g;
    public static final dx5 h;
    public static final j22 i;
    public static final j22 j;
    public static final j22 k;
    public static final j22 l;
    public static final j22 m;
    public static final j22 n;
    public static final j22 o;
    public static final j22 p;
    public static final j22 q;
    public static final j22 r;
    public static final j22 s;
    public static final j22 t;
    public static final j22 u;
    public static final Set v;
    public static final Set w;
    public static final j22 x;
    public static final j22 y;
    public static final j22 z;

    static {
        dx5 dx5Var = new dx5("kotlin");
        a = dx5Var;
        dx5 dx5VarA = dx5Var.a(t99.e("reflect"));
        b = dx5VarA;
        dx5Var.a(t99.e("experimental"));
        dx5 dx5VarA2 = dx5Var.a(t99.e("collections"));
        c = dx5VarA2;
        dx5Var.a(t99.e("sequences"));
        dx5 dx5VarA3 = dx5Var.a(t99.e("ranges"));
        d = dx5VarA3;
        dx5 dx5VarA4 = dx5Var.a(t99.e(DebugImage.JVM));
        dx5Var.a(t99.e("js"));
        dx5Var.a(t99.e("annotations")).a(t99.e(DebugImage.JVM));
        dx5VarA4.a(t99.e("internal"));
        dx5VarA4.a(t99.e("functions"));
        dx5 dx5VarA5 = dx5Var.a(t99.e("annotation"));
        e = dx5VarA5;
        dx5 dx5VarA6 = dx5Var.a(t99.e("internal"));
        dx5VarA6.a(t99.e("ir"));
        dx5 dx5VarA7 = dx5Var.a(t99.e("coroutines"));
        f = dx5VarA7;
        dx5VarA7.a(t99.e("intrinsics"));
        g = dx5Var.a(t99.e("enums"));
        dx5Var.a(t99.e("contracts"));
        dx5 dx5VarA8 = dx5Var.a(t99.e("concurrent")).a(t99.e("atomics"));
        h = dx5VarA8;
        dx5Var.a(t99.e("test"));
        dx5Var.a(t99.e("text"));
        qd0.I0(new dx5[]{dx5Var, dx5VarA2, dx5VarA3, dx5VarA5});
        qd0.I0(new dx5[]{dx5Var, dx5VarA2, dx5VarA3, dx5VarA5, dx5VarA, dx5VarA6, dx5VarA7, dx5VarA8});
        y8c.i("Nothing");
        i = y8c.i("Unit");
        j = y8c.i("Any");
        k = y8c.i("Enum");
        y8c.i("Annotation");
        l = y8c.i("Array");
        j22 j22VarI = y8c.i("Boolean");
        m = j22VarI;
        j22 j22VarI2 = y8c.i("Char");
        j22 j22VarI3 = y8c.i("Byte");
        j22 j22VarI4 = y8c.i("Short");
        j22 j22VarI5 = y8c.i("Int");
        n = j22VarI5;
        j22 j22VarI6 = y8c.i("Long");
        o = j22VarI6;
        j22 j22VarI7 = y8c.i("Float");
        j22 j22VarI8 = y8c.i("Double");
        p = y8c.r(j22VarI3);
        q = y8c.r(j22VarI4);
        r = y8c.r(j22VarI5);
        s = y8c.r(j22VarI6);
        y8c.i("CharSequence");
        t = y8c.i("String");
        y8c.i("Throwable");
        y8c.i("Cloneable");
        y8c.o("KProperty");
        y8c.o("KMutableProperty");
        y8c.o("KProperty0");
        y8c.o("KMutableProperty0");
        y8c.o("KProperty1");
        y8c.o("KMutableProperty1");
        y8c.o("KProperty2");
        y8c.o("KMutableProperty2");
        u = y8c.o("KFunction");
        y8c.o("KClass");
        y8c.o("KCallable");
        y8c.o("KType");
        cn1.V(t99.e("Sequence")).a.c();
        y8c.i("Comparable");
        y8c.i("Number");
        y8c.i("Function");
        cn1.V(t99.e("SuspendFunction")).a.c();
        Set setI0 = qd0.I0(new j22[]{j22VarI, j22VarI2, j22VarI3, j22VarI4, j22VarI5, j22VarI6, j22VarI7, j22VarI8});
        v = setI0;
        qd0.I0(new j22[]{j22VarI3, j22VarI4, j22VarI5, j22VarI6});
        Set set = setI0;
        int iF = bm8.F(t72.u(set, 10));
        if (iF < 16) {
            iF = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(iF);
        for (Object obj : set) {
            linkedHashMap.put(obj, y8c.n(((j22) obj).f()));
        }
        y8c.l(linkedHashMap);
        Set setI1 = qd0.I0(new j22[]{p, q, r, s});
        w = setI1;
        Set set2 = setI1;
        int iF2 = bm8.F(t72.u(set2, 10));
        LinkedHashMap linkedHashMap2 = new LinkedHashMap(iF2 >= 16 ? iF2 : 16);
        for (Object obj2 : set2) {
            linkedHashMap2.put(obj2, y8c.n(((j22) obj2).f()));
        }
        y8c.l(linkedHashMap2);
        Set set3 = v;
        Set set4 = w;
        LinkedHashSet linkedHashSetM = n3d.m(set3, set4);
        j22 j22Var = t;
        n3d.n(linkedHashSetM, j22Var);
        dx5 dx5Var2 = f;
        t99 t99VarE = t99.e("Continuation");
        dx5Var2.getClass();
        dx5 dx5Var3 = dx5.c;
        cn1.V(t99VarE).a.c();
        cn1.V(t99.e("CoroutineContext")).a.c();
        y8c.j("Iterator");
        y8c.j("Iterable");
        y8c.j("Collection");
        y8c.j("List");
        y8c.j("ListIterator");
        y8c.j("Set");
        j22 j22VarJ = y8c.j("Map");
        y8c.j("AbstractMap");
        y8c.j("MutableIterator");
        y8c.j("CharIterator");
        y8c.j("MutableIterable");
        y8c.j("MutableCollection");
        x = y8c.j("MutableList");
        y8c.j("MutableListIterator");
        y = y8c.j("MutableSet");
        j22 j22VarJ2 = y8c.j("MutableMap");
        z = j22VarJ2;
        j22VarJ.d(t99.e("Entry"));
        j22VarJ2.d(t99.e("MutableEntry"));
        y8c.i("Result");
        dx5 dx5Var4 = d;
        t99 t99VarE2 = t99.e("IntRange");
        dx5Var4.getClass();
        cn1.V(t99VarE2).a.c();
        cn1.V(t99.e("LongRange")).a.c();
        cn1.V(t99.e("CharRange")).a.c();
        dx5 dx5Var5 = e;
        t99 t99VarE3 = t99.e("AnnotationRetention");
        dx5Var5.getClass();
        cn1.V(t99VarE3).a.c();
        cn1.V(t99.e("AnnotationTarget")).a.c();
        y8c.i("DeprecationLevel");
        A = new j22(g, t99.e("EnumEntries"));
        j22 j22VarH = y8c.h("AtomicBoolean");
        j22 j22VarH2 = y8c.h("AtomicInt");
        j22 j22VarH3 = y8c.h("AtomicLong");
        y8c.h("AtomicReference");
        iy9 iy9Var = new iy9(m, j22VarH);
        j22 j22Var2 = n;
        iy9 iy9Var2 = new iy9(j22Var2, j22VarH2);
        j22 j22Var3 = o;
        bm8.H(iy9Var, iy9Var2, new iy9(j22Var3, j22VarH3));
        y8c.h("AtomicArray");
        bm8.H(new iy9(j22Var2, y8c.h("AtomicIntArray")), new iy9(j22Var3, y8c.h("AtomicLongArray")));
        n3d.n(n3d.n(n3d.n(n3d.n(n3d.m(set3, set4), j22Var), i), j), k);
    }
}
