package defpackage;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class swg {
    public static final tx0 a;
    public static final tx0 b;
    public static final tx0 c;
    public static final tx0 d;
    public static final tx0 e;
    public static final tx0 f;
    public static final tx0 g;
    public static final tx0 h;
    public static final tx0 i;
    public static final tx0 j;
    public static final tx0 k;
    public static final tx0 l;
    public static final tx0 m;
    public static final tx0 n;
    public static final tx0 o;
    public static final tx0 p;
    public static final tx0 q;

    static {
        i iVarA = tx0.a();
        iVarA.a = 3;
        iVarA.c = "Google Play In-app Billing API version is less than 3";
        iVarA.a();
        i iVarA2 = tx0.a();
        iVarA2.a = 3;
        iVarA2.c = "Google Play In-app Billing API version is less than 9";
        iVarA2.a();
        i iVarA3 = tx0.a();
        iVarA3.a = 3;
        iVarA3.c = "Billing service unavailable on device.";
        a = iVarA3.a();
        i iVarA4 = tx0.a();
        iVarA4.a = 2;
        iVarA4.c = "Billing service unavailable on device.";
        b = iVarA4.a();
        i iVarA5 = tx0.a();
        iVarA5.a = 5;
        iVarA5.c = "Client is already in the process of connecting to billing service.";
        c = iVarA5.a();
        i iVarA6 = tx0.a();
        iVarA6.a = 5;
        iVarA6.c = "The list of SKUs can't be empty.";
        iVarA6.a();
        i iVarA7 = tx0.a();
        iVarA7.a = 5;
        iVarA7.c = "SKU type can't be empty.";
        iVarA7.a();
        i iVarA8 = tx0.a();
        iVarA8.a = 5;
        iVarA8.c = "Product type can't be empty.";
        d = iVarA8.a();
        i iVarA9 = tx0.a();
        iVarA9.a = -2;
        iVarA9.c = "Client does not support extra params.";
        e = iVarA9.a();
        i iVarA10 = tx0.a();
        iVarA10.a = 5;
        iVarA10.c = "Invalid purchase token.";
        iVarA10.a();
        i iVarA11 = tx0.a();
        iVarA11.a = 6;
        iVarA11.c = "An internal error occurred.";
        f = iVarA11.a();
        i iVarA12 = tx0.a();
        iVarA12.a = 5;
        iVarA12.c = "SKU can't be null.";
        iVarA12.a();
        i iVarA13 = tx0.a();
        iVarA13.a = 0;
        g = iVarA13.a();
        i iVarA14 = tx0.a();
        iVarA14.a = -1;
        iVarA14.c = "Service connection is disconnected.";
        h = iVarA14.a();
        i iVarA15 = tx0.a();
        iVarA15.a = 2;
        iVarA15.c = "Timeout communicating with service.";
        i = iVarA15.a();
        i iVarA16 = tx0.a();
        iVarA16.a = -2;
        iVarA16.c = "Client does not support subscriptions.";
        j = iVarA16.a();
        i iVarA17 = tx0.a();
        iVarA17.a = -2;
        iVarA17.c = "Client does not support subscriptions update.";
        iVarA17.a();
        i iVarA18 = tx0.a();
        iVarA18.a = -2;
        iVarA18.c = "Client does not support get purchase history.";
        iVarA18.a();
        i iVarA19 = tx0.a();
        iVarA19.a = -2;
        iVarA19.c = "Client does not support price change confirmation.";
        iVarA19.a();
        i iVarA20 = tx0.a();
        iVarA20.a = -2;
        iVarA20.c = "Play Store version installed does not support cross selling products.";
        iVarA20.a();
        i iVarA21 = tx0.a();
        iVarA21.a = -2;
        iVarA21.c = "Client does not support multi-item purchases.";
        k = iVarA21.a();
        i iVarA22 = tx0.a();
        iVarA22.a = -2;
        iVarA22.c = "Client does not support offer_id_token.";
        l = iVarA22.a();
        i iVarA23 = tx0.a();
        iVarA23.a = -2;
        iVarA23.c = "Play Store version installed does not support gift code purchase.";
        m = iVarA23.a();
        i iVarA24 = tx0.a();
        iVarA24.a = -2;
        iVarA24.c = "Client does not support ProductDetails.";
        n = iVarA24.a();
        i iVarA25 = tx0.a();
        iVarA25.a = -2;
        iVarA25.c = "Client does not support launching subscription management action flow.";
        iVarA25.a();
        i iVarA26 = tx0.a();
        iVarA26.a = -2;
        iVarA26.c = "Client does not support in-app messages.";
        iVarA26.a();
        i iVarA27 = tx0.a();
        iVarA27.a = -2;
        iVarA27.c = "Client does not support user choice billing.";
        iVarA27.a();
        i iVarA28 = tx0.a();
        iVarA28.a = -2;
        iVarA28.c = "Play Store version installed does not support external offer.";
        iVarA28.a();
        i iVarA29 = tx0.a();
        iVarA29.a = -2;
        iVarA29.c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        iVarA29.a();
        i iVarA30 = tx0.a();
        iVarA30.a = -2;
        iVarA30.c = "Play Store version installed does not support querying AutoPay plan purchase.";
        iVarA30.a();
        i iVarA31 = tx0.a();
        iVarA31.a = -2;
        iVarA31.c = "Play Store version installed does not support including suspended subscriptions.";
        iVarA31.a();
        i iVarA32 = tx0.a();
        iVarA32.a = 5;
        iVarA32.c = "Unknown feature";
        iVarA32.a();
        i iVarA33 = tx0.a();
        iVarA33.a = -2;
        iVarA33.c = "Play Store version installed does not support get billing config.";
        iVarA33.a();
        i iVarA34 = tx0.a();
        iVarA34.a = -2;
        iVarA34.c = "Query product details with serialized docid is not supported.";
        iVarA34.a();
        i iVarA35 = tx0.a();
        iVarA35.a = -2;
        iVarA35.c = "Play Store version installed does not support launching external offer flow.";
        iVarA35.a();
        i iVarA36 = tx0.a();
        iVarA36.a = 4;
        iVarA36.c = "Item is unavailable for purchase.";
        o = iVarA36.a();
        i iVarA37 = tx0.a();
        iVarA37.a = -2;
        iVarA37.c = "Query product details with developer specified account is not supported.";
        iVarA37.a();
        i iVarA38 = tx0.a();
        iVarA38.a = -2;
        iVarA38.c = "Play Store version installed does not support alternative billing only.";
        iVarA38.a();
        i iVarA39 = tx0.a();
        iVarA39.a = 5;
        iVarA39.c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        p = iVarA39.a();
        i iVarA40 = tx0.a();
        iVarA40.a = 6;
        iVarA40.c = "An error occurred while retrieving billing override.";
        q = iVarA40.a();
        i iVarA41 = tx0.a();
        iVarA41.a = -2;
        iVarA41.c = "Play Store version installed does not support the provided billing program.";
        iVarA41.a();
        i iVarA42 = tx0.a();
        iVarA42.a = -2;
        iVarA42.c = "Play Store version installed does not support launching external links.";
        iVarA42.a();
        i iVarA43 = tx0.a();
        iVarA43.a = 5;
        iVarA43.c = "A DeveloperProvidedBillingListener must be provided when initializing the BillingClient in order to use multiple payment options for this billing program.";
        iVarA43.a();
        i iVarA44 = tx0.a();
        iVarA44.a = 5;
        iVarA44.c = "A listener must be provided calling this method.";
        iVarA44.a();
        i iVarA45 = tx0.a();
        iVarA45.a = -2;
        iVarA45.c = "Play Store version installed does not support show billing program information dialog.";
        iVarA45.a();
        i iVarA46 = tx0.a();
        iVarA46.a = -2;
        iVarA46.c = "Play Store version installed does not support get billing choice info.";
        iVarA46.a();
    }

    public static tx0 a(int i2, String str) {
        i iVarA = tx0.a();
        iVarA.a = i2;
        iVarA.c = str;
        return iVarA.a();
    }
}
