package defpackage;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes.dex */
public abstract class v0g {
    public static final z60 a;
    public static final z60 b;
    public static final z60 c;

    static {
        new z60("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK", 0);
        new z60("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER", 0);
        new z60("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE", 4);
        new z60("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS", 1);
        new z60("START_SAFE_BROWSING", "START_SAFE_BROWSING", 5);
        new z60("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST", 5);
        new z60("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new z60("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST", 5);
        new z60("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new z60("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL", 5);
        new z60("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE", 1);
        new z60("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE", 1);
        new z60("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS", 1);
        new z60("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS", 1);
        new z60("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1);
        new z60("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1);
        new z60("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR", 0);
        new z60("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR", 0);
        new z60("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS", 1);
        new z60("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT", 5);
        new z60("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT", 1);
        new z60("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0);
        new z60("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE", 0);
        new z60("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 5);
        new z60("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED", 5);
        new z60("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 5);
        new z60("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE", 0);
        new z60("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE", 0);
        new z60("WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER", 2);
        new z60("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0);
        new z60("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL", 0);
        new z60("POST_WEB_MESSAGE", "POST_WEB_MESSAGE", 0);
        new z60("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0);
        new z60("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT", 4);
        new z60("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT", 4);
        new z60("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER", 7);
        new z60("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE", 7);
        new z60("TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE", 6);
        new yzd();
        new yzd();
        new yzd();
        new z60("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 7);
        new t0g();
        new z60("PROXY_OVERRIDE", "PROXY_OVERRIDE:3", 2);
        a = new z60("MULTI_PROCESS", "MULTI_PROCESS_QUERY", 2);
        new z60("FORCE_DARK", "FORCE_DARK", 7);
        new z60("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR", 2);
        new z60("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER", 2);
        b = new z60("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1", 2);
        new z60("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS", 2);
        new z60("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER", 2);
        new z60("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2);
        new z60("GET_COOKIE_INFO", "GET_COOKIE_INFO", 2);
        new z60("REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST", 2);
        new z60("USER_AGENT_METADATA", "USER_AGENT_METADATA", 2);
        new u0g("USER_AGENT_METADATA_FORM_FACTORS", "USER_AGENT_METADATA", 0);
        new u0g("MULTI_PROFILE", "MULTI_PROFILE", 1);
        new z60("ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR", 2);
        new z60("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS", 2);
        new z60("MUTE_AUDIO", "MUTE_AUDIO", 2);
        new z60("WEB_AUTHENTICATION", "WEB_AUTHENTICATION", 2);
        new z60("SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING", 2);
        new z60("BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE", 2);
        new z60("BACK_FORWARD_CACHE_SETTINGS", "BACK_FORWARD_CACHE_SETTINGS", 2);
        new z60("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V3", "BACK_FORWARD_CACHE_SETTINGS_V3", 2);
        new z60("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V4", "BACK_FORWARD_CACHE_SETTINGS_V4", 2);
        new z60("DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA", 2);
        String str = "PREFETCH_URL_V5";
        new u0g(str, "PREFETCH_URL_V5", 2);
        new z60("ASYNC_WEBVIEW_STARTUP_V2");
        new z60("ASYNC_WEBVIEW_STARTUP");
        new z60("ASYNC_WEBVIEW_STARTUP_ASYNC_STARTUP_LOCATIONS");
        new z60("DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING", 2);
        new z60("PRERENDER_URL_V2", "PRERENDER_URL_V3", 2);
        new z60("SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2", 2);
        new z60("PREFETCH_CACHE_V1", "PREFETCH_CACHE_V1", 2);
        new z60("PREFETCH_WITH_CALLBACK_RESULT_V1");
        new z60("SET_MAX_PRERENDERS_V1", "SET_MAX_PRERENDERS_V1", 2);
        new z60("SAVE_STATE", "SAVE_STATE", 2);
        new z60("NAVIGATION_GET_WEB_RESOURCE_ERROR", "NAVIGATION_GET_WEB_RESOURCE_ERROR", 2);
        new z60("NAVIGATION_LISTENER", "PAGE_GET_URL", 2);
        c = new z60("PROVIDER_WEAKLY_REF_WEBVIEW", "PROVIDER_WEAKLY_REF_WEBVIEW", 2);
        new z60("PAYMENT_REQUEST", "PAYMENT_REQUEST", 2);
        new z60("WEBVIEW_BUILDER_EXPERIMENTAL_V1", "WEBVIEW_BUILDER_V1", 2);
        new z60("WEBVIEW_BUILDER_EXPERIMENTAL_V2", "WEBVIEW_BUILDER_V2", 2);
        new z60("COOKIE_INTERCEPT", "COOKIE_INTERCEPT", 2);
        new z60("WARM_UP_RENDERER_PROCESS", "WARM_UP_RENDERER_PROCESS", 2);
        new z60("CUSTOM_REQUEST_HEADERS", "CUSTOM_REQUEST_HEADERS", 2);
        new yzd();
        new yzd();
        new yzd();
        new z60("PRECONNECT", "PRECONNECT", 2);
        new z60("ENQUEUE_PRECONNECT", "ENQUEUE_PRECONNECT", 2);
        new z60("ADD_QUIC_HINTS", "ADD_QUIC_HINTS_V1", 2);
        new z60("HYPERLINK_CONTEXT_MENU_ITEMS", "HYPERLINK_CONTEXT_MENU_ITEMS", 2);
        new z60("JS_INJECTION_IN_FRAME_AND_WORLD", "JS_INJECTION_IN_FRAME_AND_WORLD", 2);
        new z60("WEBVIEW_NAVIGATE_EXPERIMENTAL_V1", "WEBVIEW_NAVIGATE_V1", 2);
        new z60("DOWNLOAD_FAVICONS_ENABLED", "DOWNLOAD_FAVICONS_ENABLED", 2);
        new z60("HTTP_CACHE_MANAGER", "HTTP_CACHE_MANAGER", 2);
    }

    public static boolean a(String str) {
        Set<a70> setUnmodifiableSet = Collections.unmodifiableSet(a70.c);
        HashSet<a70> hashSet = new HashSet();
        for (a70 a70Var : setUnmodifiableSet) {
            if (a70Var.a.equals(str)) {
                hashSet.add(a70Var);
            }
        }
        if (hashSet.isEmpty()) {
            ho7.n("Unknown feature ".concat(str));
            return false;
        }
        for (a70 a70Var2 : hashSet) {
            if (a70Var2.a() || a70Var2.b()) {
                return true;
            }
        }
        return false;
    }
}
