package defpackage;

import java.util.Iterator;
import java.util.Map;
import tech.chatmind.api.ArcanaGroup;
import tech.chatmind.api.TarotCardType;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class vhe {
    public static final fl8 a;
    public static final Map b;
    public static final Map c;

    static {
        fl8 fl8Var = new fl8();
        TarotCardType tarotCardType = TarotCardType.THE_FOOL;
        lie lieVar = lie.a;
        fl8Var.put(tarotCardType, lieVar);
        fl8Var.put(TarotCardType.THE_MAGICIAN, lieVar);
        TarotCardType tarotCardType2 = TarotCardType.THE_HIGH_PRIESTESS;
        lie lieVar2 = lie.b;
        fl8Var.put(tarotCardType2, lieVar2);
        TarotCardType tarotCardType3 = TarotCardType.THE_EMPRESS;
        lie lieVar3 = lie.d;
        fl8Var.put(tarotCardType3, lieVar3);
        TarotCardType tarotCardType4 = TarotCardType.THE_EMPEROR;
        lie lieVar4 = lie.c;
        fl8Var.put(tarotCardType4, lieVar4);
        fl8Var.put(TarotCardType.THE_HIEROPHANT, lieVar3);
        fl8Var.put(TarotCardType.THE_LOVERS, lieVar);
        fl8Var.put(TarotCardType.THE_CHARIOT, lieVar2);
        fl8Var.put(TarotCardType.STRENGTH, lieVar4);
        fl8Var.put(TarotCardType.THE_HERMIT, lieVar3);
        fl8Var.put(TarotCardType.JUSTICE, lieVar);
        fl8Var.put(TarotCardType.THE_HANGED_MAN, lieVar2);
        fl8Var.put(TarotCardType.DEATH, lieVar2);
        fl8Var.put(TarotCardType.TEMPERANCE, lieVar4);
        fl8Var.put(TarotCardType.THE_DEVIL, lieVar3);
        fl8Var.put(TarotCardType.THE_TOWER, lieVar4);
        fl8Var.put(TarotCardType.THE_STAR, lieVar);
        fl8Var.put(TarotCardType.THE_MOON, lieVar2);
        fl8Var.put(TarotCardType.THE_SUN, lieVar4);
        fl8Var.put(TarotCardType.JUDGEMENT, lieVar4);
        fl8Var.put(TarotCardType.THE_WORLD, lieVar3);
        Iterator<T> it = ArcanaGroup.Wands.getTypes().iterator();
        while (it.hasNext()) {
            fl8Var.put((TarotCardType) it.next(), lieVar4);
        }
        Iterator<T> it2 = ArcanaGroup.Cups.getTypes().iterator();
        while (it2.hasNext()) {
            fl8Var.put((TarotCardType) it2.next(), lieVar2);
        }
        Iterator<T> it3 = ArcanaGroup.Swords.getTypes().iterator();
        while (it3.hasNext()) {
            fl8Var.put((TarotCardType) it3.next(), lieVar);
        }
        Iterator<T> it4 = ArcanaGroup.Pentacles.getTypes().iterator();
        while (it4.hasNext()) {
            fl8Var.put((TarotCardType) it4.next(), lieVar3);
        }
        a = fl8Var.j();
        iy9 iy9Var = new iy9(TarotCardType.THE_FOOL, tie.v);
        TarotCardType tarotCardType5 = TarotCardType.THE_MAGICIAN;
        tie tieVar = tie.c;
        iy9 iy9Var2 = new iy9(tarotCardType5, tieVar);
        TarotCardType tarotCardType6 = TarotCardType.THE_HIGH_PRIESTESS;
        tie tieVar2 = tie.b;
        iy9 iy9Var3 = new iy9(tarotCardType6, tieVar2);
        TarotCardType tarotCardType7 = TarotCardType.THE_EMPRESS;
        tie tieVar3 = tie.d;
        iy9 iy9Var4 = new iy9(tarotCardType7, tieVar3);
        TarotCardType tarotCardType8 = TarotCardType.THE_WHEEL_OF_FORTUNE;
        tie tieVar4 = tie.f;
        iy9 iy9Var5 = new iy9(tarotCardType8, tieVar4);
        iy9 iy9Var6 = new iy9(TarotCardType.THE_HANGED_MAN, tie.w);
        TarotCardType tarotCardType9 = TarotCardType.THE_TOWER;
        tie tieVar5 = tie.e;
        iy9 iy9Var7 = new iy9(tarotCardType9, tieVar5);
        TarotCardType tarotCardType10 = TarotCardType.THE_SUN;
        tie tieVar6 = tie.a;
        iy9 iy9Var8 = new iy9(tarotCardType10, tieVar6);
        iy9 iy9Var9 = new iy9(TarotCardType.JUDGEMENT, tie.x);
        TarotCardType tarotCardType11 = TarotCardType.THE_WORLD;
        tie tieVar7 = tie.g;
        iy9 iy9Var10 = new iy9(tarotCardType11, tieVar7);
        TarotCardType tarotCardType12 = TarotCardType.TWO_OF_WANDS;
        iy9 iy9Var11 = new iy9(tarotCardType12, tieVar5);
        TarotCardType tarotCardType13 = TarotCardType.THREE_OF_WANDS;
        iy9 iy9Var12 = new iy9(tarotCardType13, tieVar6);
        TarotCardType tarotCardType14 = TarotCardType.FOUR_OF_WANDS;
        iy9 iy9Var13 = new iy9(tarotCardType14, tieVar3);
        TarotCardType tarotCardType15 = TarotCardType.FIVE_OF_WANDS;
        iy9 iy9Var14 = new iy9(tarotCardType15, tieVar7);
        TarotCardType tarotCardType16 = TarotCardType.SIX_OF_WANDS;
        iy9 iy9Var15 = new iy9(tarotCardType16, tieVar4);
        TarotCardType tarotCardType17 = TarotCardType.SEVEN_OF_WANDS;
        iy9 iy9Var16 = new iy9(tarotCardType17, tieVar5);
        TarotCardType tarotCardType18 = TarotCardType.EIGHT_OF_WANDS;
        iy9 iy9Var17 = new iy9(tarotCardType18, tieVar);
        TarotCardType tarotCardType19 = TarotCardType.NINE_OF_WANDS;
        iy9 iy9Var18 = new iy9(tarotCardType19, tieVar2);
        TarotCardType tarotCardType20 = TarotCardType.TEN_OF_WANDS;
        iy9 iy9Var19 = new iy9(tarotCardType20, tieVar7);
        TarotCardType tarotCardType21 = TarotCardType.TWO_OF_CUPS;
        iy9 iy9Var20 = new iy9(tarotCardType21, tieVar3);
        TarotCardType tarotCardType22 = TarotCardType.THREE_OF_CUPS;
        iy9 iy9Var21 = new iy9(tarotCardType22, tieVar);
        TarotCardType tarotCardType23 = TarotCardType.FOUR_OF_CUPS;
        iy9 iy9Var22 = new iy9(tarotCardType23, tieVar2);
        TarotCardType tarotCardType24 = TarotCardType.FIVE_OF_CUPS;
        iy9 iy9Var23 = new iy9(tarotCardType24, tieVar5);
        TarotCardType tarotCardType25 = TarotCardType.SIX_OF_CUPS;
        iy9 iy9Var24 = new iy9(tarotCardType25, tieVar6);
        TarotCardType tarotCardType26 = TarotCardType.SEVEN_OF_CUPS;
        iy9 iy9Var25 = new iy9(tarotCardType26, tieVar3);
        TarotCardType tarotCardType27 = TarotCardType.EIGHT_OF_CUPS;
        iy9 iy9Var26 = new iy9(tarotCardType27, tieVar7);
        TarotCardType tarotCardType28 = TarotCardType.NINE_OF_CUPS;
        iy9 iy9Var27 = new iy9(tarotCardType28, tieVar4);
        TarotCardType tarotCardType29 = TarotCardType.TEN_OF_CUPS;
        iy9 iy9Var28 = new iy9(tarotCardType29, tieVar5);
        TarotCardType tarotCardType30 = TarotCardType.TWO_OF_SWORDS;
        iy9 iy9Var29 = new iy9(tarotCardType30, tieVar2);
        TarotCardType tarotCardType31 = TarotCardType.THREE_OF_SWORDS;
        iy9 iy9Var30 = new iy9(tarotCardType31, tieVar7);
        TarotCardType tarotCardType32 = TarotCardType.FOUR_OF_SWORDS;
        iy9 iy9Var31 = new iy9(tarotCardType32, tieVar4);
        TarotCardType tarotCardType33 = TarotCardType.FIVE_OF_SWORDS;
        iy9 iy9Var32 = new iy9(tarotCardType33, tieVar3);
        TarotCardType tarotCardType34 = TarotCardType.SIX_OF_SWORDS;
        iy9 iy9Var33 = new iy9(tarotCardType34, tieVar);
        TarotCardType tarotCardType35 = TarotCardType.SEVEN_OF_SWORDS;
        iy9 iy9Var34 = new iy9(tarotCardType35, tieVar2);
        TarotCardType tarotCardType36 = TarotCardType.EIGHT_OF_SWORDS;
        iy9 iy9Var35 = new iy9(tarotCardType36, tieVar4);
        TarotCardType tarotCardType37 = TarotCardType.NINE_OF_SWORDS;
        iy9 iy9Var36 = new iy9(tarotCardType37, tieVar5);
        TarotCardType tarotCardType38 = TarotCardType.TEN_OF_SWORDS;
        iy9 iy9Var37 = new iy9(tarotCardType38, tieVar6);
        TarotCardType tarotCardType39 = TarotCardType.TWO_OF_PENTACLES;
        iy9 iy9Var38 = new iy9(tarotCardType39, tieVar4);
        TarotCardType tarotCardType40 = TarotCardType.THREE_OF_PENTACLES;
        iy9 iy9Var39 = new iy9(tarotCardType40, tieVar5);
        TarotCardType tarotCardType41 = TarotCardType.FOUR_OF_PENTACLES;
        iy9 iy9Var40 = new iy9(tarotCardType41, tieVar6);
        TarotCardType tarotCardType42 = TarotCardType.FIVE_OF_PENTACLES;
        iy9 iy9Var41 = new iy9(tarotCardType42, tieVar);
        TarotCardType tarotCardType43 = TarotCardType.SIX_OF_PENTACLES;
        iy9 iy9Var42 = new iy9(tarotCardType43, tieVar2);
        TarotCardType tarotCardType44 = TarotCardType.SEVEN_OF_PENTACLES;
        iy9 iy9Var43 = new iy9(tarotCardType44, tieVar7);
        TarotCardType tarotCardType45 = TarotCardType.EIGHT_OF_PENTACLES;
        iy9 iy9Var44 = new iy9(tarotCardType45, tieVar6);
        TarotCardType tarotCardType46 = TarotCardType.NINE_OF_PENTACLES;
        iy9 iy9Var45 = new iy9(tarotCardType46, tieVar3);
        TarotCardType tarotCardType47 = TarotCardType.TEN_OF_PENTACLES;
        b = bm8.H(iy9Var, iy9Var2, iy9Var3, iy9Var4, iy9Var5, iy9Var6, iy9Var7, iy9Var8, iy9Var9, iy9Var10, iy9Var11, iy9Var12, iy9Var13, iy9Var14, iy9Var15, iy9Var16, iy9Var17, iy9Var18, iy9Var19, iy9Var20, iy9Var21, iy9Var22, iy9Var23, iy9Var24, iy9Var25, iy9Var26, iy9Var27, iy9Var28, iy9Var29, iy9Var30, iy9Var31, iy9Var32, iy9Var33, iy9Var34, iy9Var35, iy9Var36, iy9Var37, iy9Var38, iy9Var39, iy9Var40, iy9Var41, iy9Var42, iy9Var43, iy9Var44, iy9Var45, new iy9(tarotCardType47, tieVar));
        TarotCardType tarotCardType48 = TarotCardType.THE_EMPEROR;
        dle dleVar = dle.a;
        iy9 iy9Var46 = new iy9(tarotCardType48, dleVar);
        TarotCardType tarotCardType49 = TarotCardType.THE_HIEROPHANT;
        dle dleVar2 = dle.b;
        iy9 iy9Var47 = new iy9(tarotCardType49, dleVar2);
        TarotCardType tarotCardType50 = TarotCardType.THE_LOVERS;
        dle dleVar3 = dle.c;
        iy9 iy9Var48 = new iy9(tarotCardType50, dleVar3);
        TarotCardType tarotCardType51 = TarotCardType.THE_CHARIOT;
        dle dleVar4 = dle.d;
        iy9 iy9Var49 = new iy9(tarotCardType51, dleVar4);
        TarotCardType tarotCardType52 = TarotCardType.STRENGTH;
        dle dleVar5 = dle.e;
        iy9 iy9Var50 = new iy9(tarotCardType52, dleVar5);
        TarotCardType tarotCardType53 = TarotCardType.THE_HERMIT;
        dle dleVar6 = dle.f;
        iy9 iy9Var51 = new iy9(tarotCardType53, dleVar6);
        TarotCardType tarotCardType54 = TarotCardType.JUSTICE;
        dle dleVar7 = dle.g;
        iy9 iy9Var52 = new iy9(tarotCardType54, dleVar7);
        TarotCardType tarotCardType55 = TarotCardType.DEATH;
        dle dleVar8 = dle.v;
        iy9 iy9Var53 = new iy9(tarotCardType55, dleVar8);
        TarotCardType tarotCardType56 = TarotCardType.TEMPERANCE;
        dle dleVar9 = dle.w;
        iy9 iy9Var54 = new iy9(tarotCardType56, dleVar9);
        TarotCardType tarotCardType57 = TarotCardType.THE_DEVIL;
        dle dleVar10 = dle.x;
        iy9 iy9Var55 = new iy9(tarotCardType57, dleVar10);
        TarotCardType tarotCardType58 = TarotCardType.THE_STAR;
        dle dleVar11 = dle.y;
        iy9 iy9Var56 = new iy9(tarotCardType58, dleVar11);
        TarotCardType tarotCardType59 = TarotCardType.THE_MOON;
        dle dleVar12 = dle.z;
        c = bm8.H(iy9Var46, iy9Var47, iy9Var48, iy9Var49, iy9Var50, iy9Var51, iy9Var52, iy9Var53, iy9Var54, iy9Var55, iy9Var56, new iy9(tarotCardType59, dleVar12), new iy9(tarotCardType12, dleVar), new iy9(tarotCardType13, dleVar), new iy9(tarotCardType14, dleVar), new iy9(tarotCardType15, dleVar5), new iy9(tarotCardType16, dleVar5), new iy9(tarotCardType17, dleVar5), new iy9(tarotCardType18, dleVar9), new iy9(tarotCardType19, dleVar9), new iy9(tarotCardType20, dleVar9), new iy9(TarotCardType.QUEEN_OF_WANDS, dleVar), new iy9(TarotCardType.KING_OF_WANDS, dleVar5), new iy9(tarotCardType21, dleVar4), new iy9(tarotCardType22, dleVar4), new iy9(tarotCardType23, dleVar4), new iy9(tarotCardType24, dleVar8), new iy9(tarotCardType25, dleVar8), new iy9(tarotCardType26, dleVar8), new iy9(tarotCardType27, dleVar12), new iy9(tarotCardType28, dleVar12), new iy9(tarotCardType29, dleVar12), new iy9(TarotCardType.QUEEN_OF_CUPS, dleVar4), new iy9(TarotCardType.KING_OF_CUPS, dleVar8), new iy9(tarotCardType30, dleVar7), new iy9(tarotCardType31, dleVar7), new iy9(tarotCardType32, dleVar7), new iy9(tarotCardType33, dleVar11), new iy9(tarotCardType34, dleVar11), new iy9(tarotCardType35, dleVar11), new iy9(tarotCardType36, dleVar3), new iy9(tarotCardType37, dleVar3), new iy9(tarotCardType38, dleVar3), new iy9(TarotCardType.QUEEN_OF_SWORDS, dleVar7), new iy9(TarotCardType.KING_OF_SWORDS, dleVar11), new iy9(tarotCardType39, dleVar10), new iy9(tarotCardType40, dleVar10), new iy9(tarotCardType41, dleVar10), new iy9(tarotCardType42, dleVar2), new iy9(tarotCardType43, dleVar2), new iy9(tarotCardType44, dleVar2), new iy9(tarotCardType45, dleVar6), new iy9(tarotCardType46, dleVar6), new iy9(tarotCardType47, dleVar6), new iy9(TarotCardType.QUEEN_OF_PENTACLES, dleVar10), new iy9(TarotCardType.KING_OF_PENTACLES, dleVar2));
    }
}
