package defpackage;

/* JADX INFO: compiled from: r8-map-id-c0f90335ad52c1b57db77aaf4b1db5c7c9c2627f2e01f059a43261b6162c0147 */
/* JADX INFO: loaded from: classes.dex */
public abstract class xqa {
    public static final hs3 A;
    public static final hs3 A0;
    public static final hs3 B;
    public static final hs3 B0;
    public static final hs3 C;
    public static final hs3 C0;
    public static final hs3 D;
    public static final hs3 D0;
    public static final hs3 E;
    public static final hs3 E0;
    public static final hs3 F;
    public static final hs3 F0;
    public static final hs3 G;
    public static final hs3 G0;
    public static final hs3 H;
    public static final hs3 H0;
    public static final hs3 I;
    public static final hs3 I0;
    public static final hs3 J;
    public static final hs3 J0;
    public static final hs3 K;
    public static final hs3 K0;
    public static final hs3 L;
    public static final hs3 L0;
    public static final hs3 M;
    public static final hs3 M0;
    public static final hs3 N;
    public static final hs3 N0;
    public static final hs3 O;
    public static final hs3 O0;
    public static final hs3 P;
    public static final hs3 P0;
    public static final hs3 Q;
    public static final hs3 Q0;
    public static final hs3 R;
    public static final hs3 R0;
    public static final hs3 S;
    public static final hs3 S0;
    public static final hs3 T;
    public static final hs3 T0;
    public static final hs3 U;
    public static final hs3 U0;
    public static final hs3 V;
    public static final hs3 V0;
    public static final hs3 W;
    public static final hs3 W0;
    public static final hs3 X;
    public static final hs3 X0;
    public static final hs3 Y;
    public static final hs3 Y0;
    public static final hs3 Z;
    public static final hs3 Z0;
    public static final hs3 a;
    public static final hs3 a0;
    public static final hs3 a1;
    public static final hs3 b;
    public static final hs3 b0;
    public static final hs3 c;
    public static final hs3 c0;
    public static final hs3 d;
    public static final hs3 d0;
    public static final hs3 e;
    public static final hs3 e0;
    public static final hs3 f;
    public static final hs3 f0;
    public static final hs3 g;
    public static final hs3 g0;
    public static final hs3 h;
    public static final hs3 h0;
    public static final hs3 i;
    public static final hs3 i0;
    public static final hs3 j;
    public static final hs3 j0;
    public static final hs3 k;
    public static final hs3 k0;
    public static final hs3 l;
    public static final hs3 l0;
    public static final hs3 m;
    public static final hs3 m0;
    public static final hs3 n;
    public static final hs3 n0;
    public static final hs3 o;
    public static final hs3 o0;
    public static final hs3 p;
    public static final hs3 p0;
    public static final isa q;
    public static final hs3 q0;
    public static final hs3 r;
    public static final hs3 r0;
    public static final hs3 s;
    public static final hs3 s0;
    public static final hs3 t;
    public static final hs3 t0;
    public static final hs3 u;
    public static final hs3 u0;
    public static final hs3 v;
    public static final hs3 v0;
    public static final hs3 w;
    public static final hs3 w0;
    public static final hs3 x;
    public static final hs3 x0;
    public static final hs3 y;
    public static final hs3 y0;
    public static final hs3 z;
    public static final hs3 z0;

    static {
        isa isaVar = new isa("OnboardingVisited");
        Boolean bool = Boolean.FALSE;
        a = new hs3(isaVar, bool);
        b = new hs3(new isa("OnboardingFunnelStage"), "");
        c = new hs3(new isa("OnboardingCreatedAccount"), bool);
        d = new hs3(new isa("OnboardingFirstReadingQuestion"), "");
        e = new hs3(new isa("OnboardingFirstReadingDrawing"), "");
        f = new hs3(new isa("GuestReadingClaimPending"), "");
        g = new hs3(new isa("GuestReadingClaimAttempts"), 0);
        h = new hs3(new isa("PendingUserProfile"), "");
        i = new hs3(new isa("DailyNotificationTime"), "");
        j = new hs3(new isa("TomorrowNotificationTime"), "");
        k = new hs3(new isa("LastDailyNotificationTime"), "");
        l = new hs3(new isa("LastTomorrowNotificationTime"), "");
        m = new hs3(new isa("DailyFortuneCompletedDatesCache"), "");
        n = new hs3(new isa("SignUpSource"), "unknow");
        o = new hs3(new isa("SendCrashReport"), bool);
        p = new hs3(new isa("SendAdId"), bool);
        q = new isa("AppUiMode");
        r = new hs3(new isa("LastVersion"), 0);
        s = new hs3(new isa("LastMigrationVersion"), 0);
        t = new hs3(new isa("AnnualFortune2026MemberDialogShown"), bool);
        u = new hs3(new isa("ForceEnableAnnualFortune"), bool);
        v = new hs3(new isa("ForceEnableFourSeasons"), bool);
        w = new hs3(new isa("QaHomeEventBannerVisibility"), -1);
        x = new hs3(new isa("QaHomeFourSeasonsVisibility"), -1);
        y = new hs3(new isa("QaSeasonalFixtureState"), "");
        z = new hs3(new isa("AccountDisplayName"), "");
        A = new hs3(new isa("AccountId"), "");
        B = new hs3(new isa("AccountEMail"), "");
        C = new hs3(new isa("AccountUsage"), "");
        D = new hs3(new isa("FiveCardUpgradeStates"), "");
        E = new hs3(new isa("FriendCouponPendingGrants"), "");
        isa isaVar2 = new isa("FriendCouponNoticeShownAccountIds");
        xu4 xu4Var = xu4.a;
        F = new hs3(isaVar2, xu4Var);
        G = new hs3(new isa("LocallyRegisteredAccountIds"), "");
        H = new hs3(new isa("SignUpCompletedAccountIds"), xu4Var);
        I = new hs3(new isa("SignUpAnalyticsPending"), "");
        J = new hs3(new isa("FollowUpUsageConsumptionToastShownAccountIds"), "");
        K = new hs3(new isa("DailyFortuneGuideStatesJson"), "");
        L = new hs3(new isa("UserPopupPendingJson"), "");
        M = new hs3(new isa("UserPopupExposuresJson"), "");
        N = new hs3(new isa("TomorrowFortuneReminderGuideCohortCaptured"), bool);
        O = new hs3(new isa("TomorrowFortuneReminderGuideExistingInstallCohort"), bool);
        P = new hs3(new isa("AccountCompensated"), bool);
        Q = new hs3(new isa("UserHasReportAskQuestion"), bool);
        R = new hs3(new isa("LastCheckUpdateTime"), "");
        S = new hs3(new isa("LastAlertUpdateTime"), "");
        T = new hs3(new isa("HasNewVersion"), bool);
        U = new hs3(new isa("DevCustomDomain"), "");
        V = new hs3(new isa("QaClockOverrideEpochMillis"), Long.MIN_VALUE);
        W = new hs3(new isa("LastConsumedMonthEventId"), "");
        X = new hs3(new isa("LastConsumedDailyEventId"), "");
        Y = new hs3(new isa("EventsInformation"), "");
        Z = new hs3(new isa("ExploreBanners"), "");
        isa isaVar3 = new isa("ShouldShowDrawCardTips");
        Boolean bool2 = Boolean.TRUE;
        a0 = new hs3(isaVar3, bool2);
        b0 = new hs3(new isa("ShouldShowCutCardTips"), bool2);
        c0 = new hs3(new isa("LastPaywallImpressDate"), "");
        d0 = new hs3(new isa("LastActivityPopupDate"), "");
        e0 = new hs3(new isa("LastAppOpenTrackDate"), "");
        f0 = new hs3(new isa("ShareInviteAccount"), "");
        g0 = new hs3(new isa("ShareInviteCode"), "");
        h0 = new hs3(new isa("WidgetInstallTodayPendingTime"), 0L);
        i0 = new hs3(new isa("WidgetInstallQdPendingTime"), 0L);
        j0 = new hs3(new isa("LastFirebaseAppOpenTrackDate"), "");
        k0 = new hs3(new isa("LastHomepageViewTrackDate"), "");
        l0 = new hs3(new isa("ReadingLockedExposureChatIds"), xu4Var);
        m0 = new hs3(new isa("ConversationEstablishedIds"), xu4Var);
        n0 = new hs3(new isa("MixpanelAuthorizationBaselineRecorded"), bool);
        o0 = new hs3(new isa("MixpanelAuthorizationHandled"), bool);
        p0 = new hs3(new isa("SchemeType"), "");
        q0 = new hs3(new isa("NewUserFreeReadingCount"), 2);
        r0 = new hs3(new isa("EnableYearlySubUnlockAllCards"), bool);
        s0 = new hs3(new isa("ExperimentVariantsJson"), "");
        t0 = new hs3(new isa("PaywallSkusJson"), "");
        u0 = new hs3(new isa("SeasonalReadingSnapshots"), "");
        v0 = new hs3(new isa("SeasonalDrafts"), "");
        w0 = new hs3(new isa("DebugPaywallAbForcedGroup"), "");
        x0 = new hs3(new isa("DebugPaywallAbForcedUsedOffer"), bool);
        y0 = new hs3(new isa("NewTarotSkinsPopupShown"), bool);
        z0 = new hs3(new isa("GiftCardGuidePopupShown"), bool);
        A0 = new hs3(new isa("OnboardingThemeSelected"), bool);
        B0 = new hs3(new isa("WidgetOnboardingPopupShown"), bool);
        C0 = new hs3(new isa("WidgetOnboardingPopupSeenVersion"), 0);
        D0 = new hs3(new isa("WidgetGuideTodayFortuneAskCount"), 0);
        E0 = new hs3(new isa("WidgetGuideTodayFortuneOptedOut"), bool);
        F0 = new hs3(new isa("WidgetGuideQuickDecisionAskCount"), 0);
        G0 = new hs3(new isa("WidgetGuideQuickDecisionOptedOut"), bool);
        H0 = new hs3(new isa("WidgetGuideLastShownDate"), "");
        I0 = new hs3(new isa("WidgetInstallTodayFortunePendingSource"), "");
        J0 = new hs3(new isa("WidgetInstallTodayFortuneFired"), bool);
        K0 = new hs3(new isa("WidgetInstallQuickDecisionPendingSource"), "");
        L0 = new hs3(new isa("WidgetInstallQuickDecisionPendingScenario"), "");
        M0 = new hs3(new isa("WidgetInstallQuickDecisionFired"), bool);
        N0 = new hs3(new isa("MayDay2026PopupShown"), bool);
        O0 = new hs3(new isa("MayDay2026DeckResetDone"), bool);
        P0 = new hs3(new isa("IsLegacyUser"), bool);
        Q0 = new hs3(new isa("IsLegacyUserDetected"), bool);
        R0 = new hs3(new isa("NotificationTouchpoint1Shown"), bool);
        S0 = new hs3(new isa("NotificationTouchpoint2Shown"), bool);
        T0 = new hs3(new isa("NotificationTouchpoint3Shown"), bool);
        U0 = new hs3(new isa("NotificationTouchpoint4Shown"), bool);
        V0 = new hs3(new isa("LastTp1OrTp2ShownDate"), "");
        W0 = new hs3(new isa("MsgNotificationInAppEnabled"), bool2);
        X0 = new hs3(new isa("FourSeasonsLocalNotifyEnabled"), bool);
        Y0 = new hs3(new isa("FourSeasonsLocalNotifyContext"), "");
        Z0 = new hs3(new isa("FourSeasonsLocalNotifyDeliveredCampaigns"), xu4Var);
        a1 = new hs3(new isa("FourSeasonsNotifyPopupLastShownDate"), "");
    }
}
